"""Alembic migration.
Auto-generated migration to:
- Add otp_expires_at (datetime) and otp_attempts (int) to users
- Add reserved_balance (Numeric) to users
- Add transaction metadata columns to transactions
- Convert float columns (wallet_balance, budget, proposed_rate, transaction.amount) to Numeric(12,2)

IMPORTANT: Altering column types is database-specific. For PostgreSQL this performs an ALTER TYPE. For SQLite ALTER COLUMN is limited — review the generated SQL and, for production, prefer a tested manual migration.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260819_payment_and_numeric'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reserved_balance', sa.Numeric(12, 2), nullable=False, server_default='0.00'))

    op.add_column('transactions', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('payment_provider', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('account_number', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('external_trx_id', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('is_released', sa.Boolean(), nullable=True))

    # Convert float columns to Numeric(12,2)
    # Note: ALTER TYPE may not be supported on SQLite. Review and test on staging DB.
    try:
        op.alter_column('users', 'wallet_balance', type_=sa.Numeric(12, 2), existing_type=sa.Float(), existing_nullable=True)
    except Exception:
        # SQLite fallback: leave as-is and warn
        pass

    try:
        op.alter_column('jobs', 'budget', type_=sa.Numeric(12, 2), existing_type=sa.Float(), existing_nullable=False)
    except Exception:
        pass

    try:
        op.alter_column('job_applications', 'proposed_rate', type_=sa.Numeric(12, 2), existing_type=sa.Float(), existing_nullable=True)
    except Exception:
        pass

    try:
        op.alter_column('transactions', 'amount', type_=sa.Numeric(12, 2), existing_type=sa.Float(), existing_nullable=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column('transactions', 'amount', type_=sa.Float(), existing_type=sa.Numeric(12, 2), existing_nullable=False)
    except Exception:
        pass

    try:
        op.alter_column('job_applications', 'proposed_rate', type_=sa.Float(), existing_type=sa.Numeric(12, 2), existing_nullable=True)
    except Exception:
        pass

    try:
        op.alter_column('jobs', 'budget', type_=sa.Float(), existing_type=sa.Numeric(12, 2), existing_nullable=False)
    except Exception:
        pass

    try:
        op.alter_column('users', 'wallet_balance', type_=sa.Float(), existing_type=sa.Numeric(12, 2), existing_nullable=True)
    except Exception:
        pass

    op.drop_column('transactions', 'is_released')
    op.drop_column('transactions', 'idempotency_key')
    op.drop_column('transactions', 'external_trx_id')
    op.drop_column('transactions', 'account_number')
    op.drop_column('transactions', 'payment_provider')
    op.drop_column('transactions', 'type')

    op.drop_column('users', 'reserved_balance')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    # ### end Alembic commands ###
